### ISSUE TITLE
칸반보드 만들기 

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#1]
## Description

칸반 보드 만들기입니다. 

## Tasks

- [x] task 1 : proejct 생성 (칸반보드 만들기)
- [x] task 2 : issue 생성
- [x] task 3 : 칸반보드 test 

## References

- reference 1
- reference 2
