### ISSUE TITLE
크램폴린 배포 관련 자잘한 수정사항

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#105]
## Description

크램폴린 배포 관련 자잘한 파일들 수정하기 

## Tasks

- [x] task 1 : mysql 관련 파일 다듬기 
  - [x] subTask :  필요없는 환경 변수 지우기
  - [x] subTask : yaml template 다듬기  
- [ ] task 2
- [ ] task 3

## References

- reference 1 : [mysql root 계정 관련](https://velog.io/@june20516/mysql-dockerize1-%EB%8F%84%EC%BB%A4%EB%A1%9C-mysql-container-%EB%9D%84%EC%9A%B0%EA%B8%B0)
- reference 2
