### ISSUE TITLE
모집글 구현 

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#12]
## Description

모집글 목록 조회 구현 및 모집글 CRUD 구현 

- 모집글 목록 조회는 무한 스크롤 구현할 예정입니다. 
- 모집글 목록 조회, 모집글 상세 조회는 로그인 필요 없습니다. 
- 모집글 등록, 수정, 삭제는 로그인 필요합니다. 

## Tasks
- [x] task 0 
  - [x] task 0-0 : Post Class 작성 
  - [x] task 0-1 : PostRequest 작성 
  - [x] task 0-2 : PostResponse 작성 
- [x] task 1 : 모집글 목록 조회 구현
- [x] task 2 : 모집글 CRUD 구현 
  - [x] task 2-1 : 모집글 등록 구현
  - [x] task 2-2 : 모집글 상세 조회 구현
  - [x] task 2-3 : 모집글 수정 구현
  - [x] task 2-4 : 모집글 삭제 구현  

## References

- reference 1 : 전체적인 개발 흐름 
https://velog.io/@yu-jin-song/SpringBoot-%EA%B2%8C%EC%8B%9C%ED%8C%90-%EA%B5%AC%ED%98%84-1-Entity-%EB%B0%8F-Repository-%EA%B5%AC%ED%98%84

- reference 2 : record 사용 
https://s7won.tistory.com/2

- reference 3: boolean vs Boolean
https://ratseno.tistory.com/101

- spring validation annotation 정리 
https://hyeran-story.tistory.com/81

- 컬럼의 기본값 default value 설정하기
https://velog.io/@minji/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-JPA-%EC%97%94%ED%8B%B0%ED%8B%B0-%EC%BB%AC%EB%9F%BC-default-value-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0-ColumnDefault-Builder.Default-%EC%B0%A8%EC%9D%B4
