### ISSUE TITLE
점수 관련 버그 수정 

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#123]
## Description

- 점수 조회 시 자신이 등록한 점수만 가져올 수 있게 합니다. 
- 점수 수정 및 삭제 시 권한 확인을 자신이 작성한 모집글인지 확인하는 것에서  자신이 등록한 점수인지 확인하는 것으로 변경합니다. 
- 점수 수정 및 삭제 시 예외처리를 분리하였습니다. 

## Tasks

- [x] task 1 : 점수 조회 시 자신의 점수만 가져올 수 있게 변경 
- [x] task 2 : 점수 수정 및 삭제 시 자신이 등록한 점수인지 확인 
- [x] task 3 : 점수 수정 및 삭제 시 예외처리 분리 

## References

- reference 1
- reference 2
