### ISSUE TITLE
서버 시간대 맞추기

### ISSUE THREAD

**Issue by jagaldol** [Step3-kakao-tech-campus/Team3_BE#29]
## Description

![image](https://github.com/Step3-kakao-tech-campus/Team3_BE/assets/84557643/2dd89063-9db0-45a7-8b8d-357a024a79c4)

서버 시간대를 맞추어야 합니다.

db에 저장되는 시간은 UST 시간으로 저장되고 있습니다. 한국시간으로 맞추기 위해서는 전부 9시간을 더해야 올바른 시간이 나옵니다.

"테스트4입니다." 게시글이 5주차 전체회의에서 실시간으로 만들었던 모집글입니다.

이를 보시면 자동으로 default now() 값을 저장하는 createdAt과 editedAt이 전부 UST 시간대로 들어가고 있습니다. 로컬 mysql(한국 컴퓨터)을 사용해서 테스트를 해보고 어느 부분의 시간대가 문제가 되고 있는지 파악하여 설정 수정이 필요합니다.

## Tasks

- [x] 로컬 환경 테스트하기
- [x] 서버 환경 테스트하기
- [x] KST로 시간대 설정 변경
