### ISSUE TITLE
4주차 멘토 피드백 사항 정리

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#31]
## Description
- **s3에 이미지 업로드 방식** 
  - 서버를 거쳐서 이미지를 검증하는 방식으로 구현 
  - aws 계정 생성 및 s3구축 필요 
- **모집글 목록 조회** 
  - QueryDSL 사용해서 나중에 코드 리팩토링 할 때 수정하기 
- **response header에 url 담아서 보내기** 
  - 안하기로 함 
  - post에서는 response body에 postId 담아서 보내주기 
  - status code는 200으로 맞추기 
  - 프론트랑 같이 논의해봐야 할 점 
- **N+1 문제** 
  - JPA에서 모든 연관 관계를 맺을 필요가 없음  
  - 최대한 단방향으로 맺기  
  - 성능 최적화 할 때 고려해야 할 사항  
  - 연관관계 최소화하고 관계를 끊어서 두 번에 나눠서 쿼리 보내기  

## Tasks

- [x] **task 1 : s3 사용**  
  - [x] subTask : aws 계정 생성  
  - [x] subTask : s3 구축 
  - [x] subTask : 서버 생성하고 접속 관련 처리하기 
- [ ] **task 2 : 모집글 목록 조회** 
  - [ ] subTask : QueryDSL 공부 및 적용 
- [x] **task 3 : response header 양식 통일** 
  - [x] subTask : response header 코드 수정 
  - [x] subTask : api 명세 수정 
  - [x] subTask : 프론트와의 논의  
- [x] **task 4 : N+1 문제** 
  - [x] subTask : JPA 연관관계 정리 
  - [x] subTask : 코드 수정하기  

## References

- reference 1
- reference 2
