### ISSUE TITLE
점수 CRUD 구현 

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#32]
## Description
점수 등록, 조회, 수정, 삭제 기능을 개발합니다. 

## Tasks

- [x] task 1 : s3 구축하기 
- [x] task 2 : 이미지 업로드 플로우 설계 
- [x] task 3 : 점수 등록 
- [x] task 4 : 점수 조회
- [x] task 5 : 점수 수정
- [x] task 6 : 점수 삭제 

## References

- [multipart/form-data 이해하기](https://lena-chamna.netlify.app/post/http_multipart_form-data/)
- [multipartFiie 업로드 구현](https://kindloveit.tistory.com/112)
- [multipartFile 업로드 구현 2](https://velog.io/@yu-jin-song/SpringBoot-%EA%B2%8C%EC%8B%9C%ED%8C%90-%EA%B5%AC%ED%98%84-4-MultipartFile-%EB%8B%A4%EC%A4%91-%ED%8C%8C%EC%9D%BC%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%97%85%EB%A1%9C%EB%93%9C)
- [s3 구축하기](https://velog.io/@songs4805/AWS-S3-%EB%B2%84%ED%82%B7-%EC%83%9D%EC%84%B1)
- [s3 권한](https://somaz.tistory.com/180)
- [s3 암호화](https://kimjingo.tistory.com/190)
- [s3에 파일을 업로드하는 3가지 방법](https://songsong.dev/entry/S3%EC%97%90-%ED%8C%8C%EC%9D%BC%EC%9D%84-%EC%97%85%EB%A1%9C%EB%93%9C%ED%95%98%EB%8A%94-%EC%84%B8-%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95)
- [s3 이미지 업로드 플로우](https://yiminwook.tistory.com/m/29)
- [s3 관련 정보들](https://www.surfit.io/tag/AWS%20S3)
- [s3 퍼블릭 액세스 차단 설정](https://medium.com/opsnow-security/amazon-s3-%EB%B2%84%ED%82%B7-%ED%8D%BC%EB%B8%94%EB%A6%AD-%EC%B0%A8%EB%8B%A8-%EC%84%A4%EC%A0%95-feat-cloudfront-oac-9a5636cada28)
- [s3 파일 업로드](https://www.sunny-son.space/spring/Springboot%EB%A1%9C%20S3%20%ED%8C%8C%EC%9D%BC%20%EC%97%85%EB%A1%9C%EB%93%9C/)
- [s3 파일 업로드 2](https://pangsblog.tistory.com/72)
- [시큐어 코딩 - 파일 업로드](https://myeonguni.tistory.com/1646)
