### ISSUE TITLE
모집글 관련 피드백 반영하기 

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#33]
## Description
- Post class에서 현재 승인된 사람 for문에서 stream으로 변경 
- postRepository에서 isClose false인 것 말고 모집 기한이 현재보다 과거일 때도 반영되게 코드 수정하기 
- post Create, Update 시에 response header에 url 반환하지 않고, response body에 postId 주기 
- status 200으로 통일 
- 모집글 update 일어나면 updatedAt에 요청 들어온 시각으로 변경하기 
- 모집글 마감 api 구현 (마감 버튼만 누르면 바로 마감되게 할 수 있게)

## Tasks

- [x] task 1 : getCurrnetNumber 수정 
- [x] task 2 : PostRepository 수정 
- [x] task 3 : PostController Create, Update 함수 수정 
  - [x] subTask : 다른 Controller도 보면서 같이 수정하기  
- [x] task 4 : update 요청 시각으로 변경 
- [x] task 5 : post 등록 response body에 pk 주기
- [x] task 6 : 모집글 마감 api 구현하기 

## References

- reference 1
- reference 2
