### ISSUE TITLE
점수 등록에서 이미지 없이 점수만 등록 가능하도록 변경

### ISSUE THREAD

**Issue by jagaldol** [Step3-kakao-tech-campus/Team3_BE#43]
## Description

현재 점수 등록 api의 경우 점수와 이미지를 여러 개 동시에 받을 수 있습니다. 

scores와 images의 리스트로 점수들과 이미지들을 받아 각 index에 따라 둘을 매칭시켜 업로드 하는 방식으로 구현되어 있습니다.

따라서 api 사용자는 점수 3개 입력 시 이미지 3개를 필수로 입력해야하는 문제가 발생합니다.

이미지없이 점수만을 업로드도 가능하도록 api 변경이 필요합니다.

## Task
- [x] Task 1 : 점수 등록 API 수정 
  - [x] subTask : 단일 파일 업로드 반영
  - [x] subTask : 사진 없어도 등록 가능한 것 반영 
- [x] Task 2 : 점수 등록 로직 수정 
  - [x] subTask : 단일 파일 업로드로 수정 
  - [x] subTask : 사진 없어도 등록 가능하도록 수정

**Comment by sososo0** [comment]
점수 등록에서 다중 파일 업로드에서 단일 파일 업로드로 변경하기
