### ISSUE TITLE
5주차 멘토 피드백 사항 정리 

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#58]
## Description
- **남은 기간 역할 분배** 
  - 크램폴린 배포 
  - 남은 API 구현 
  - 코드 점검 

- **성능 테스트 방법** 
  - 간단한 방법
    - 로그를 찍기
    - print로 시간을 찍어서 확인
  - 현재 3조의 경우 대부분의 부하는 쿼리에서 발생
  - 스프링부하테스트 검색 / 참고 : Jmeter
 
- **기타 조언 및 추천** 
  - N+1 문제가 발생하는 것은 대부분 연관관계가 잘못맺어 있을 확률이 대부분
  - 문서 관리로 깃헙 WIKI 추천 
    - 들어가면 좋을 내용 : sequence diagram, 회의록, 트러블 슈팅, api 문서 
    - [참고](https://github.com/TEAM-ARK/sprout-backend/wiki)
  - 에러 처리 개선
    - Exception400, 500처럼 나누는 것은 비추
    - Exception의 이름을 명확히 정해주어 상황에 맞게 디테일하게 사용하기
  - 의미없이 반복되는 코드 개선
  - 메소드명 수정
    - 참고 검색 키워드) 명령-쿼리 분리 법칙
    - 팁) 변수, 메소드명 지을 때 GPT사용해보는 것도 좋을 듯
  - 유틸 코드에 대해서 자신만의 기준 세우기 
    - [관련 참고 자료](https://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html)
  -  사진 업로드시 용량 제한 
    - 서비스, 서버 사양에 따라
    - 사진 일반적으로 10메가바이트로 설정하는 듯
  - s3업로드 확장자 검사
    - 클라이언트, 서버 둘다
    - .jpg, .png 등을 리스트에 넣어 놓고 contain 메소드 사용하면 검사코드가 더욱 간결해질듯
  - 팁) IntelliJ 자동정렬 기능을 주기적으로 사용해주면 좋음
    - 윈도우: ctrl+shift+alt+L
    - 맥: command+option+L
  - IntelliJ 플러그인 추천)
    - Transalation - 번역 (공식지원플러그인이라 자바독 같은 것도 번역 잘해줌)
    - SonarLint - 정적코드분석 (비효율적인 코드→ 변환된 코드추천)
    - CodeMetrics - 코드 복잡도(메소드나 클래스별 코드복잡도 숫자도 알려줌→ 빨갛다면 수정필요할 가능성up)
    - GitToolBox
    - code with me - 화면,코드 공유

참고) 트랜잭션 → 기본은 부모트랜잭션을 따라감, 레벨을 변경할 수 있음

## Tasks

- [x] task 1 : 크램폴린 배포 
- [x] task 2 : 남은 API 구현 
- [x] task 3 : 전체적인 코드 점검 
- [ ] task 4 : 멘토님 조언 및 추천 반영 
   - [ ] subTask 1 : 성능 테스트 
   - [x] subTask 2 : 문서화 
   - [x] subTask 3 : 예외 처리 개선 
   - [x] subTask 4 : 연관 관계 잘 확인  

## References

- reference 1
- reference 2
