### ISSUE TITLE
post 엔티티, 참여 기록, 신청자 목록 버그 수정

### ISSUE THREAD

**Issue by xcelxlorx** [Step3-kakao-tech-campus/Team3_BE#59]
## Description
- post 엔티티의 getCurrentNumber()에서 데이터가 중복 조회되고 있습니다. 
- 참여 기록 key 요청이 안된다고 합니다.
- 참여 기록 멤버에 참여 기록 조회 대상 추가 요청이 있습니다. 
- 신청자 목록에서 신청 개수에 오류가 있습니다. 

## Tasks

- [ ] post 엔티티 getCurrentNumber() 중복 데이터 제거
- [ ] 참여 기록 조회 key 에러 수정 
- [ ] 참여 기록 멤버에 조회 대상 추가
- [ ] 신청자 목록 에러 수정
