### ISSUE TITLE
가짜 데이터를 주는 GET api들 작성

### ISSUE THREAD

**Issue by jagaldol** [Step3-kakao-tech-campus/Team3_BE#6]
## Description

프론트분들이 UI 작업 시 바로 사용할 수 있도록 빠르게 가짜 데이터 서버를 만들어 배포합니다.

entity 없이 빠르게 controller 위에서 요청시 항상 같은 데이터를 주는 더미 api를 만듭니다.

## Tasks

- [x] 각 주소별 GET 요청에 대한 ResponseDto를 생성
- [x] 각 GET api들에 대한 더미 데이터를 controller 위에서 바로 하드 코딩하여 서버 제작
- [x] **프론트가 랜더링할 때 api를 통해 DTO를 사용할 수 있도록** 더미 api 서버 바로 배포
