### ISSUE TITLE
크램폴린 배포

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#62]
## Description
크램폴린 배포 방식을 이해하고, 크램폴린을 통해 서비스를 배포합니다. 

## Tasks

- [ ] task 1 : 크램폴린 배포 방식 공부 
  - [ ] subTask : 크램폴린 배포 흐름 이해하기
- [ ] task 2 : Kubernetes 공부 
- [ ] task 3 : Dockerfile 작성 

## References

- reference 1 : 쉽게 시작하는 쿠버네티스 (도서) 
- reference 2
