### ISSUE TITLE
6주차 멘토 피드백 사항 정리

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#71]
## Description

- 크램폴린 배포 
  - 카카오 ide 문의에 직접 문의하는 것이 정확 

- jpa specification 
  - OneToMany 구조에서 Fetch Join과 Pagination을 함께 사용할 때 발생하는 문제
  - 실제 나가는 쿼리를 항상 확인해보기
  - ManyToOne으로 변경해서 조회가능한지 확인
  - Fetch Join을 쓰지않고 쿼리를 분리해서 조회가능한지 확인
  - Batch Size를 조절해서 한번의 쿼리로 지연로딩을 수행할 수 있는지 확인

- Custom Exception을 일정한 예외처리를 반환할 수 있도록 하는 변경작업
  - 백엔드 개발자끼리 논의가 되어야할 문제
  - 우리 서비스가 엄격한 예외 구성을 통해 각 케이스별로 다른 예외를 발생시킬 것인지?
  - 현재처럼 모든 예외를 하나의 커스텀 예외로 래핑할 것인지?

## Tasks

- [x] task 1 : 크램폴린 배포 
- [x] task 2 : jpa specification 
- [x] task 3 : custom exception 논의 및 적용 

## References

- reference 1
- reference 2
