### ISSUE TITLE
점수 API 개선

### ISSUE THREAD

**Issue by sososo0** [Step3-kakao-tech-campus/Team3_BE#82]
## Description

기존의 점수 API를 개선합니다. 

## Tasks

- [x] task 1 : 점수 수정 API 개선 
  - [x] situation 1 : 점수(숫자)만 수정  
  - [x] situation 2 : 점수(숫자), 이미지 모두 수정 (이미지 수정은 update만 의미)
  - [x] situation 3 : 이미지만 수정 (이미지 수정은 update만 의미) 
- [x] task 2 : 점수 이미지 삭제 API 추가 - 점수 이미지만 삭제하고 싶은 경우 반영 
- [x] task 3 : 점수 삭제 API 버그 
  - [x] situation : 점수(숫자)만 등록된 점수 삭제 시 오류 발생 
- [x] task 4 : 유효성 검사  

#### 버그 발생 사진
![image](https://github.com/Step3-kakao-tech-campus/Team3_BE/assets/94467302/ea603b60-92ac-47bd-94cc-b8cd90601f41)

## References

- reference 1
- reference 2
